# Generated by Django 3.2.4 on 2021-06-17 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(null=True, upload_to='profesores/img')),
                ('video', models.FileField(null=True, upload_to='profesores/video')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
            ],
            options={
                'ordering': ('apellidos',),
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True)),
                ('titulo', models.CharField(max_length=150)),
                ('subtitulo', models.CharField(max_length=150)),
                ('fecha_inicio', models.CharField(max_length=150)),
                ('fecha_fin', models.CharField(max_length=150)),
                ('logo', models.ImageField(null=True, upload_to='curso')),
                ('alumnos', models.ManyToManyField(to='orla.Alumno')),
            ],
            options={
                'ordering': ('titulo',),
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(null=True, upload_to='profesores/img')),
                ('video', models.FileField(null=True, upload_to='profesores/video')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
            ],
            options={
                'ordering': ('apellidos',),
            },
        ),
        migrations.CreateModel(
            name='Orla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True)),
                ('titulo', models.CharField(max_length=150)),
                ('modelo', models.ImageField(null=True, upload_to='curso')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orla.curso')),
            ],
            options={
                'ordering': ('titulo',),
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='profesores',
            field=models.ManyToManyField(to='orla.Profesor'),
        ),
    ]
