# Generated by Django 3.2.4 on 2021-06-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orla', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orla',
            name='titulo3',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
