# Generated by Django 3.2.4 on 2021-06-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orla', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='imagen',
            field=models.ImageField(null=True, upload_to='alumnos/img'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='video',
            field=models.FileField(null=True, upload_to='alumnos/video'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='logo',
            field=models.ImageField(null=True, upload_to='cursos/img'),
        ),
        migrations.AlterField(
            model_name='orla',
            name='modelo',
            field=models.ImageField(null=True, upload_to='orla/modelos'),
        ),
    ]
