# Generated by Django 3.2.4 on 2021-06-18 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orla', '0002_orla_titulo3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orla',
            name='titulo3',
        ),
    ]
