# Generated by Django 3.2.4 on 2021-06-17 23:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orla', '0004_auto_20210618_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='orla',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orla',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10),
        ),
        migrations.AddField(
            model_name='orla',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
