# Generated by Django 3.2.4 on 2021-06-17 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orla', '0005_auto_20210618_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='fecha_fin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='curso',
            name='fecha_inicio',
            field=models.DateTimeField(),
        ),
    ]
